DROP TABLE dish IF EXISTS;
DROP TABLE menu IF EXISTS;
DROP TABLE role IF EXISTS;
DROP TABLE vote IF EXISTS;
DROP TABLE users IF EXISTS;
DROP TABLE restaurant IF EXISTS;

DROP SEQUENCE GLOBAL_SEQUENCE IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQUENCE
  AS INTEGER
  START WITH 10000;

CREATE TABLE restaurant
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQUENCE PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL
);

CREATE TABLE menu
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQUENCE PRIMARY KEY,
  name             VARCHAR(100)            NOT NULL,
  date             TIMESTAMP               NOT NULL,
  restaurant_id    INT                     NOT NULL,
  FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE
);

CREATE TABLE dish
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQUENCE PRIMARY KEY,
  name             VARCHAR(100)            NOT NULL,
  price            INT                     NOT NULL,
  menu_id          INT                     NOT NULL,
  FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE
);

CREATE TABLE users
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQUENCE PRIMARY KEY,
  name             VARCHAR(255)            NOT NULL,
  email            VARCHAR(255)            NOT NULL,
  password         VARCHAR(255)            NOT NULL,
  registered       TIMESTAMP DEFAULT now() NOT NULL,
  enabled          BOOLEAN DEFAULT TRUE    NOT NULL
);
CREATE UNIQUE INDEX users_unique_email_idx ON USERS (email);

CREATE TABLE role
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQUENCE PRIMARY KEY,
  user_id          INTEGER                 NOT NULL,
  role             VARCHAR(255)            NOT NULL,
  CONSTRAINT user_roles_idx UNIQUE (user_id, role),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE vote
(
  id               INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQUENCE PRIMARY KEY,
  date_time        TIMESTAMP DEFAULT now() NOT NULL,
  user_id          INTEGER                 NOT NULL,
  restaurant_id    INTEGER                 NOT NULL,
  CONSTRAINT votes_idx UNIQUE (user_id, date_time, restaurant_id),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE
);